id: P234C36A3
initial_creation_type: ocr
source_metadata:
  volumes:
    e909e7f398344aad8744e656c2491415:
      base_file: v079.txt
      image_group_id: I1PD95924
      title: ཆོས་མངོན་པའི་མཛོད་ཀྱི་བཤད་པ།
      total_pages: 1433
      volume_number: 79
